// facts.js -- WFH health facts for the Today-view fact card (sourced from clinical literature)
export const WFH_HEALTH_FACTS = [
  "<strong>The 5-Minute Rule:</strong> Walking for just 5 minutes every half hour significantly lowers blood sugar spikes by up to 58% and reduces blood pressure. <br><span class='fact-source'>Source: Duran, A.T., et al. (2023). <em>MSSE</em>. [<a href='https://pubmed.ncbi.nlm.nih.gov/36728338/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>The Danger of the Desk:</strong> Average working adults spend approximately 60% of their waking hours—equivalent to more than 8 hours a day—in a sedentary state. <br><span class='fact-source'>Source: Matthews, C.E., et al. (2008). <em>Am J Epidemiol</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC3527832/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>Enzyme Shutdown:</strong> Just 24 to 48 hours of physical inactivity drastically down-regulates crucial muscle enzymes like lipoprotein lipase (LPL) by up to 90%. <br><span class='fact-source'>Source: Bey, L., & Hamilton, M.T. (2006). <em>J Appl Physiol</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC2343229/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>You Can't Out-Train the Chair:</strong> Individuals who meet standard weekly exercise guidelines still remain at an elevated risk if they sit for extended, uninterrupted blocks. <br><span class='fact-source'>Source: Owen, N., et al. (2011). <em>Diabetes Care</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC3404815/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>Hydration Matters:</strong> A reduction of just 2% in total body weight due to water loss significantly impairs physical strength and cognitive focus. <br><span class='fact-source'>Source: Riebl, S.K., & Davy, B.M. (2007). <em>J Athl Train</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC4207053/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>The Tech Toll:</strong> Screen-focused postures average 3 hours daily, creating forward head tilt and rounded shoulders (Upper Crossed Syndrome). <br><span class='fact-source'>Source: Russin, N.H., et al. (2020). [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC12841205/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>Boost Your Mood:</strong> Hourly walking breaks of 5 minutes reduce subjective fatigue by 25% while improving positive mood, work engagement, and attention. <br><span class='fact-source'>Source: Diaz, K.M., Murdock, M.E., Serafini, M.A., et al. <em>Br J Sports Med</em>. [<a href='https://bjsm.bmj.com/content/early/2026/06/16/bjsports-2025-111221' target='_blank' rel='noopener'>Source Link</a>]</span>",
  "<strong>Arterial Calcification:</strong> Each additional hour of sitting increases your likelihood of coronary artery calcification, which restricts blood flow. <br><span class='fact-source'>Source: Lim, S.S., et al. (2015). <em>J Am Coll Cardiol</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC12755600/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>Sedentary Job Trends:</strong> About 80 percent of jobs in the United States are now mostly sedentary, compared to only 20 percent in 1950. <br><span class='fact-source'>Source: Gremaud, A.L., et al. (2011). <em>PLoS ONE</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC6064890/' target='_blank' rel='noopener'>PubMed Link</a>]</span>",
  "<strong>Sedentary Time Baseline:</strong> Americans spend an average of 7.7 hours a day sitting down, with older adults averaging closer to 9 hours daily. <br><span class='fact-source'>Source: Matthews, C.E., et al. (2008). <em>Am J Epidemiol</em>. [<a href='https://pmc.ncbi.nlm.nih.gov/articles/PMC3527832/' target='_blank' rel='noopener'>PubMed Link</a>]</span>"
];
